# Generated by Django 3.0.5 on 2020-09-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20200925_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
